check-leaks: true
color: true
extension:
  - 'js'
file:
  - './test/mixins/QueryableResourceMixin-test.js'
  - './test/mixins/QueryableCollectionMixin-test.js'
  - './test/query/Query-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
# spec: 'test/**/**/*-test.js'
watch: true
